EbayAdminSideWebSite-AlyMomdouhBranch1/EbayView/Controllers/Admins/AdminController.cs
namespace EbayView.Controllers.Admins
{
    using AutoMapper;
    using EbayView.Models.ViewModel.Account;
    using EbayView.Models.ViewModel.admns;
    using global::Models;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    public class AdminsController : Controller
    {
        private readonly IAdminRepository _AdminRepository;
        private readonly IMapper _mapper;
        public AdminsController(IAdminRepository AdminRepository, IMapper mapper)
        {
            _AdminRepository = AdminRepository;
            _mapper = mapper;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var Admins = await _AdminRepository.GetAdminAsync(); 
            var result = _mapper.Map<List<GetAdminsOutputModel>>(Admins); 
            return View(result);
        }
        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            var Admin = await _AdminRepository.GetAdminDetailsAsync(id);
            var result = _mapper.Map<GetAdminDetailsOutputModel>(Admin);    
            return View(result);
        }  
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAdminInputModel model)
        {
            try
            {
                var Admin = _mapper.Map<Admin>(model);
                await _AdminRepository.AddAdminAsync(Admin);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var Admin = await _AdminRepository.GetAdminDetailsAsync(id);
            var result = _mapper.Map<GetAdminDetailsOutputModel>(Admin);
            ViewBag.selectedadmin = result;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken] 
        public async Task<IActionResult> Edit(CreateAdminInputModel model)
        {
            try
            {
                var Admin = _mapper.Map<Admin>(model);
                await _AdminRepository.UpdateAdminAsync(Admin);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Edit),new {id= model.AdminId });
            }
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            //var Admin = await _AdminRepository.GetAdminDetailsAsync(id);
            //var result = _mapper.Map<GetAdminDetailsOutputModel>(Admin);
            //return View(result);
            var Admin = await _AdminRepository.GetAdminDetailsAsync(id);
            await _AdminRepository.DeleteAdminAsync(Admin);
            return RedirectToAction(nameof(Index));
        }

        #region //some comment
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> PostDelete(int id)
        //{
        //    try
        //    {
        //        var Admin = await _AdminRepository.GetAdminDetailsAsync(id);
        //        await _AdminRepository.DeleteAdminAsync(Admin);
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //[HttpGet,ActionName("Login")]
        //public ActionResult Login()
        //{
        //    return View();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public  IActionResult  Login(PostLoginModel model)
        //{
        //    try
        //    {
        //        // write your code here
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return RedirectToAction(nameof(Login));
        //    }
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult register(PostLoginModel model)
        //{
        //    try
        //    {
        //        // write your code here
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return RedirectToAction(nameof(Login));
        //    }
        //}
        #endregion 
    }
}

EbayAdminSideWebSite-AlyMomdouhBranch1/EbayView/Controllers/Brands/BrandsController.cs
namespace EbayView.Controllers.Brands
{
    using AutoMapper;
    using EbayView.Models.ViewModel.Brands;
    using global::Models;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    //finshed  slove all problem
    public class BrandsController : Controller   
    {
        private readonly IBrandRepository _BrandRepository;
        private readonly IMapper _mapper;
        public BrandsController(IBrandRepository BrandRepository, IMapper mapper)
        {
            _BrandRepository = BrandRepository;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var Brands = await _BrandRepository.GetBrandsAsync(); 
            var result = _mapper.Map<List<GetBrandsOutputModel>>(Brands); 
            return View(result);
        }

        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {// beause ahmed not get any thing 
            var Brand = await _BrandRepository.GetBrandDetailsAsync(id);
            var result = _mapper.Map<GetBrandDetailsOutputModel>(Brand);
            return View(result);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBrandInputModel model)
        {
            var Brand = _mapper.Map<Brands>(model);
            await _BrandRepository.AddBrandAsync(Brand);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Brands brand = await _BrandRepository.GetBrandDetailsAsync(id);
            var result = _mapper.Map<GetBrandDetailsOutputModel>(brand);
            //return View(result);
            // add by aly 
            ViewBag.oldbrand = result;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CreateBrandInputModel model)
        {
            var Brand = _mapper.Map<Brands>(model);
            await _BrandRepository.UpdateBrandAsync(Brand);
            return RedirectToAction(nameof(Index));
        } 
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            //Brands brand = await _BrandRepository.GetBrandDetailsAsync(id);
            //var result = _mapper.Map<GetBrandDetailsOutputModel>(brand); 
            //return View(result);
            var brand = await _BrandRepository.GetBrandDetailsAsync(id);
            await _BrandRepository.DeleteBrandAsync(brand);
            return RedirectToAction(nameof(Index));
        }

        //[HttpPost]// ahmed
        //[HttpPost, ActionName("Delete")]// aly
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> PostDelete(int id)
        //{
        //    try
        //    {
        //        var brand = await _BrandRepository.GetBrandDetailsAsync(id);
        //        await _BrandRepository.DeleteBrandAsync(brand);
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

EbayAdminSideWebSite-AlyMomdouhBranch1/EbayView/Controllers/HomeController.cs
using AutoMapper;
using EbayView.Models;
using EbayView.Models.ViewModel;
using EbayView.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Models;
using System.Diagnostics;
using System.Text.Json;
using System.Threading.Tasks;

namespace EbayView.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductRepository _productRepository;
        private readonly IHomeRepository _homeRepository;
        private readonly IMapper _mapper;

        public HomeController(ILogger<HomeController> logger
            , IProductRepository productRepository, IHomeRepository homeRepository,
            IMapper mapper)
        { 
                _productRepository = productRepository;
            _homeRepository = homeRepository;
            _mapper = mapper;
             
        }

        [HttpGet] 
        public async Task<IActionResult> Index()
        {
            //if (TempData["admin"] != null)
            if (HttpContext.Session.GetObjectFromJson("admin") !=null)
                {
                //object o = TempData.Peek("admin");
                //ViewBag.admin= (o == null ? null : JsonSerializer.Deserialize<Admin>((string)o));
                //HttpContext.Session.GetObjectFromJson
                var dataCount = await _homeRepository.GetDataCountAsync();
                var result = _mapper.Map<GetStatisticsOutputModel>(dataCount);
                //TempData.Keep("admin");
                return View(result);
            }
            else
            {
                //return RedirectToAction("Login","Accounts");
                return RedirectToAction("Signin", "Account");
                
            }
        } 
        //public IActionResult Privacy()
        //{
        //    return View();
        //} 
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EbayAdminSideWebSite-AlyMomdouhBranch1/EbayView/Controllers/Offers/OffersController.cs
namespace EbayView.Controllers.Offers
{
    using AutoMapper;
    using EbayView.Models.ViewModel.Offers;
    using EbayView.Models.ViewModel.Products;
    using global::Models;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    public class OffersController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly IOfferRepository _OfferRepository;
        private readonly IMapper _mapper;
        public OffersController(IOfferRepository OfferRepository, IMapper mapper
                                ,IProductRepository productRepository)
        {
            _OfferRepository = OfferRepository;
            _productRepository = productRepository;
            _mapper = mapper;
        } 
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var Offers = await _OfferRepository.GetOffersAsync(); 
            var result = _mapper.Map<List<GetOfferOutputModel>>(Offers); 
            return View(result);
        }

        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            var Offer = await _OfferRepository.GetOfferDetailsAsync(id);
            var result = _mapper.Map<GetOfferDetailsOutputModel>(Offer);
            return View(result);
        }
        [HttpGet]
          public async Task<ActionResult> Create()
        //public  ActionResult  Create()
        {
            //add by aly 
            var products = await _productRepository.GetProductsAsync();
            var AllproductsResult =   _mapper.Map<List<GetProductsOutputModel>>(products);
           // if (AllproductsResult.Count >0) { 
            if (AllproductsResult!=null)
                {
                    ViewBag.AvailableProducts = AllproductsResult; 
                    return View();
            }
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateOffersInputModel model)
        {
            //try
           // {
                var Offer = _mapper.Map<Offers>(model);
                await _OfferRepository.AddOfferAsync(Offer);
                return RedirectToAction(nameof(Index));
           // }
            //catch
            //{
            //    return View();
            //}
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var Offer = await _OfferRepository.GetOfferDetailsAsync(id);
            var result = _mapper.Map<GetOfferDetailsOutputModel>(Offer);
            //return View(result);
            // by aly 
            ViewBag.selectoffer = result;
            var products = await _productRepository.GetProductsAsync();
            var AllproductsResult = _mapper.Map<List<GetProductsOutputModel>>(products);  
                ViewBag.AvailableProducts = AllproductsResult;
                return View(); 
        } 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CreateOffersInputModel model)
        {
            try
            {
                var Offer = _mapper.Map<Offers>(model);
                await _OfferRepository.UpdateOfferAsync(Offer);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Offers Offer = await _OfferRepository.GetOfferDetailsAsync(id);
            //var result = _mapper.Map<GetOfferDetailsOutputModel>(Offer); 
            //return View(result);
            // by aly 
                         await _OfferRepository.DeleteOfferAsync(Offer);
            return RedirectToAction(nameof(Index));
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostDelete(int id)
        {
            try
            {
                var Offer = await _OfferRepository.GetOfferDetailsAsync(id);
                await _OfferRepository.DeleteOfferAsync(Offer);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

EbayAdminSideWebSite-AlyMomdouhBranch1/EbayView/Controllers/Users/UserController.cs
namespace EbayView.Controllers.Users
{
    using AutoMapper;
    using EbayView.Models.ViewModel.Users;
    using global::Models;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    public class UsersController : Controller
    {
        private readonly IUserRepository _UserRepository;
        private readonly IMapper _mapper;
        public UsersController(IUserRepository UserRepository, IMapper mapper)
        {
            _UserRepository = UserRepository;
            _mapper = mapper;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var Users = await _UserRepository.GetUserAsync(); 
            var result = _mapper.Map<List<GetUsersOutputModel>>(Users); 
            return View(result);
        }
        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            var User = await _UserRepository.GetUserDetailsAsync(id);
            var result = _mapper.Map<GetUsserDetailsOutputModel>(User);
            return View(result);
        } 
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            //var User = await _UserRepository.GetUserDetailsAsync(id);
            //var result = _mapper.Map<GetUsserDetailsOutputModel>(User);
            //return View(result);

            // add by aly
            try
            {
                var User = await _UserRepository.GetUserDetailsAsync(id);
                await _UserRepository.DeleteUserAsync(User);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public async Task<IActionResult> sendemail(int id)
        {
            var User = await _UserRepository.GetUserDetailsAsync(id);
            var userinfo = _mapper.Map<GetUsserDetailsOutputModel>(User);
            return RedirectToAction("index", "Mail", userinfo);
        }
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> PostDelete(int id)
        //{
        //    try
        //    {
        //        var User = await _UserRepository.GetUserDetailsAsync(id);
        //        await _UserRepository.DeleteUserAsync(User);
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

EbayAdminSideWebSite-AlyMomdouhBranch1/EbayView/Views/Home/Index.cshtml
@model EbayView.Models.ViewModel.GetStatisticsOutputModel

@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styleslink
{
    @*<h1>User Info</h1>*@
     @*<link href="~/css/homeindex.css" rel="stylesheet"/> *@
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
       <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
     
     <style>
         a{
              color:white;
              text-decoration:none;
         }
     </style>
}
@*  
<div class="market-updates">
			<div class="col-md-4 market-update-gd">
				<div class="market-update-block clr-block-1">
					<div class="col-md-8 market-update-left">
						<h3> </h3>
						<h4>Registered User</h4> 
					</div>
					<div class="col-md-4 market-update-right">
						 <img src="~/img/RegisteredUser.png"/>
					</div>
				  <div class="clearfix"> </div>
				</div>
			</div>
			<div class="col-md-4 market-update-gd">
				<div class="market-update-block clr-block-2">
				 <div class="col-md-8 market-update-left">
					<h3>135</h3>
					<h4>Daily Visitors</h4>
					<p>Other hand, we denounce</p>
				  </div>
					<div class="col-md-4 market-update-right">
						<i class="fa fa-eye"> </i> 
					</div>
				  <div class="clearfix"> </div>
				</div>
			</div>
			<div class="col-md-4 market-update-gd">
				<div class="market-update-block clr-block-3">
					<div class="col-md-8 market-update-left">
						<h3>23</h3>
						<h4>New product</h4>
						<p>the new product add to website</p>
					</div>
					<div class="col-md-4 market-update-right"> 
						<img src="~/img/newproduct.png" />
					</div>
				  <div class="clearfix"> </div>
				</div>
			</div><div class="clearfix"> </div>
</div>
*@
<div class="tab-content">
	<div class="tab-pane tabs-animation fade active show" id="tab-content-1" role="tabpanel">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-3 bg-primary widget-chart text-white card-border">
                    <div class="icon-wrapper rounded-circle">
                        <div class="icon-wrapper-bg bg-white opacity-1"></div>
                        <i class="lnr lnr-user text-white"></i>
                    </div>
                    <div class="widget-numbers">3</div>
                    <div class="widget-subheading">Total Users</div>
                    <div class="widget-description text-success">
                        <a href="@Url.Action("Index", "Users")">
                            <i class="fa fa-angle-up "> </i>
                            <span class="pl-1">view</span>
                        </a> 
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-3 bg-success widget-chart text-white card-border"> 
                    <div class="icon-wrapper rounded-circle" style="border-radius:50%;background-color: lightgreen;">
                        <div class="icon-wrapper-bg opacity-10"></div> 
                        @*<i class="fas fa-users-cog  text-success"></i>*@
                          <img style="width:50px;display:block;margin:auto;"
                            src="https://img.icons8.com/external-itim2101-fill-itim2101/64/000000/external-admin-network-technology-itim2101-fill-itim2101-1.png"/>
                     </div>
                    <div class="widget-numbers">@Model.AdminCount</div>
                    <div class="widget-subheading">Admin</div>
                    <div class="widget-description text-white">
                        <a href="@Url.Action("Index", "Admins")">
                            <span class="pr-1">view</span>
                            <i class="fa fa-arrow-left "> </i>
                        </a>       
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-3 bg-warning widget-chart text-white card-border">
                    <div class="icon-wrapper rounded-circle">
                        <div class="icon-wrapper-bg bg-white opacity-2"></div>
                        @*<i class="lnr-laptop-phone text-white"></i>*@
                        <img  style="width:30px;display:block;margin:auto;"
                        src="https://img.icons8.com/external-sbts2018-mixed-sbts2018/58/000000/external-new-product-cyber-monday-sbts2018-mixed-sbts2018.png"/>
                    </div>
                    <div class="widget-numbers">@Model.ProductCount</div>
                    <div class="widget-subheading">New Product </div>
                    <div class="widget-description text-white"> 
                         <a href="@Url.Action("Index", "Products")">
                             <span class="pl-1">view</span>
                            <i class="fa fa-arrow-left"> </i> 
                        </a> 
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-3 bg-focus widget-chart text-white card-border">
                    <div class="icon-wrapper rounded-circle">
                        <div class="icon-wrapper-bg bg-info opacity-5"></div>
                        <img style="width:30px;display:block;margin:auto;"
                        src="https://img.icons8.com/office/16/000000/category.png"/>
                    </div>
                    <div class="widget-numbers">@Model.CategoryCount</div>
                    <div class="widget-subheading">Total Categories</div>
                    <div class="widget-description text-info"> 
                        <a href="@Url.Action("Index", "Categories")">
                            <i class="fa fa-arrow-right"> </i>
                            <span class="pl-1">view</span>
                        </a> 
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-3 bg-danger widget-chart text-white card-border">
                    <div class="icon-wrapper rounded">
                        <div class="icon-wrapper-bg bg-white opacity-2"></div>
                        <i class="lnr lnr-list text-white"></i> 
                    </div>
                    <div class="widget-numbers">@Model.SubCategoryCount</div>
                    <div class="widget-subheading">Total SubCategory</div>
                    <div class="widget-description text-white"> 
                        <a href="@Url.Action("Index", "SubCategories")">
                            <i class="fa fa-angle-up"> </i>
                            <span class="pl-1">view</span>
                        </a> 
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-3 bg-info widget-chart text-white card-border">
                    <div class="icon-wrapper rounded">
                        <div class="icon-wrapper-bg bg-focus opacity-5"></div>
                        <img  style="width:50px;display:block;margin:auto;"
                         src="https://img.icons8.com/external-outline-geotatah/64/000000/external-brand-brand-positioning-outline-geotatah-6.png"/>
                     </div>
                    <div class="widget-numbers">@Model.BrandCount</div>
                    <div class="widget-subheading">Total Brand</div>
                    <div class="widget-description text-white">
                        <a href="@Url.Action("Index", "Brands")">
                            <i class="fa fa-arrow-right"> </i>
                            <span class="pl-1">view</span>
                        </a>  
                    </div>
                </div>
            </div>
        </div>
        <div class="divider mt-0" style="margin-bottom: 30px;"></div>
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-3 bg-arielle-smile widget-chart text-white card-border">
                    <div class="icon-wrapper rounded-circle">
                        <div class="icon-wrapper-bg bg-white opacity-10"></div>
                        <i class="lnr-cog icon-gradient bg-arielle-smile"></i>
                    </div>
                    <div class="widget-numbers">@Model.OfferCount</div>
                    <div class="widget-subheading">Total Offers in Website</div>
                    <div class="widget-description text-dark">
                        <a href="@Url.Action("Index", "Offers")">
                            <i class="fa fa-angle-up "> </i>
                            <span class="pl-1">view</span>
                        </a> 
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-3 bg-warm-flame widget-chart text-white card-border">
                    <div class="icon-wrapper rounded">
                        <div class="icon-wrapper-bg bg-white opacity-10"></div>
                        <i class="lnr-screen icon-gradient bg-warm-flame"></i>
                    </div>
                    <div class="widget-numbers">@Model.StockCount</div>
                    <div class="widget-subheading">Stock places</div>
                    <div class="widget-description text-white">
                        <a href="@Url.Action("Index", "Stocks")">
                            <span class="pr-1">view</span>
                            <i class="fa fa-arrow-left "> </i>
                        </a> 
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-3 bg-ripe-malin widget-chart text-white card-border">
                    <div class="icon-wrapper rounded">
                        <div class="icon-wrapper-bg bg-white opacity-2"></div>
                        <i class="lnr-laptop-phone text-white"></i>
                    </div>
                    <div class="widget-numbers">@Model.ShipperCount</div>
                    <div class="widget-subheading">Shipper Companies</div>
                    <div class="widget-description text-white">
                        <a href="@Url.Action("Index", "Shippers")">
                            <span class="pl-1">view</span>
                            <i class="fa fa-angle-up "> </i>
                        </a> 
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-3 bg-mixed-hopes widget-chart text-white card-border">
                    <div class="icon-wrapper rounded">
                        <div class="icon-wrapper-bg bg-dark opacity-9"></div>
                        <i class="lnr-graduation-hat text-white"></i>
                    </div>
                    <div class="widget-numbers">@Model.OrderCount</div>
                    <div class="widget-subheading">Total Orders</div>
                    <div class="widget-description text-dark">
                        <a href="@Url.Action("Index", "Orders")">
                            <i class="fa fa-arrow-right "> </i>
                            <span class="pl-1">view</span></div>
                        </a>
                </div>
            </div> 
            <div class="col-md-4">
                <div class="card mb-3 bg-grow-early widget-chart text-white card-border">
                    <div class="icon-wrapper rounded-circle">
                        <div class="icon-wrapper-bg bg-white opacity-2"></div>
                        <i class="lnr-laptop-phone text-white"></i>
                    </div>
                    <div class="widget-numbers">@Model.CommentCount</div>
                    <div class="widget-subheading">Total Comment</div>
                    <div class="widget-description text-white">
                        <a href="@Url.Action("Index", "Comment")">
                            <span class="pl-1">view</span>
                            <i class="fa fa-angle-up "> </i>
                        </a>
                    </div>
                </div>
            </div>
            @*  
            <div class="col-md-4">
                <div class="card mb-3 bg-plum-plate widget-chart text-white card-border">
                    <div class="icon-wrapper rounded-circle">
                        <div class="icon-wrapper-bg bg-dark opacity-9"></div>
                        <i class="lnr-graduation-hat text-white"></i>
                    </div>
                    <div class="widget-numbers">63.2k</div>
                    <div class="widget-subheading">Bugs Fixed</div>
                    <div class="widget-description text-white opacity-8">
                        <i class="fa fa-arrow-right ">
            
                        </i>
                        <span class="pl-1">175.5%</span></div>
                </div>
            </div>
            *@
        </div>
    </div>
</div>